package application.information_handler;

import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.representer.Representer;

import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Utility class for converting and processing abstract information to/from YAML format.
 * This class provides comprehensive YAML handling capabilities for Model-Based Testing,
 * including serialization of information holders, file processing, and data retrieval.
 * 
 * <p>Key functionalities include:
 * <ul>
 *   <li>Serializing Java objects to YAML format</li>
 *   <li>Loading and parsing YAML files</li>
 *   <li>Processing YAML files (removing metadata, formatting)</li>
 *   <li>Configuring YAML output options for consistency</li>
 * </ul>
 * 
 */
public class InformationConvertertoAbstract {

    // Configuration YAML initialisée une seule fois
    private static final DumperOptions options;
    private static final Yaml yaml;

    static {
        options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        options.setExplicitStart(false);
        yaml = new Yaml(new Representer(options), options);
    }

    /**
     * Removes the first line (typically global tags) from a YAML file.
     * This method is used to clean up YAML files generated by the framework,
     * removing auto-generated metadata tags that may interfere with comparison.
     * 
     * @param filePath the absolute path to the YAML file to process
     */
    public static void removeGlobalTagsYaml(String filePath) {
        try {
            Path path = Paths.get(filePath).toAbsolutePath();
            if (!Files.exists(path)) {
                System.err.println("File not found: " + path);
                return;
            }

            String updatedContent = Files.lines(path)
                    .skip(1)
                    .collect(Collectors.joining(System.lineSeparator()));

            Files.write(path, updatedContent.getBytes());
            System.out.println("First line removed successfully from " + filePath);
        } catch (IOException e) {
            System.err.println("Error processing file " + filePath);
            e.printStackTrace();
        }
    }

    /**
     * Serializes a Java object to YAML format and writes it to a file.
     * This method converts information holder objects and other data structures
     * into YAML format for storage and later comparison during testing.
     * 
     * @param obj the Java object to serialize (typically an information holder)
     * @param filePath the absolute path where the YAML file should be created
     */
    public static void serializeToYAML(Object obj, String filePath) {
        try {
            Path path = Paths.get(filePath).toAbsolutePath();
            Files.createDirectories(path.getParent());
            
            try (FileWriter writer = new FileWriter(filePath)) {
                yaml.dump(obj, writer);
                System.out.println("YAML file created: " + path);
            }
        } catch (IOException e) {
            System.err.println("Failed to write YAML to " + filePath);
            e.printStackTrace();
        }
    }

    /**
     * Configures global YAML formatting options.
     * This method ensures consistent YAML output formatting across the framework,
     * setting block style, pretty printing, and other formatting preferences.
     */
    public static void configureYAML() {
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        options.setExplicitStart(false);
    }

    /**
     * Retrieves and parses YAML information from a file.
     * This method loads YAML files and converts them to Java Map structures
     * for processing and comparison during Model-Based Testing.
     * 
     * @param yamlFilePath the absolute path to the YAML file to load
     * @return a Map containing the parsed YAML data, or null if loading failed
     */
    public static Map<String, Object> retreiveYamlInformation(String yamlFilePath) {
        try {
            Path path = Paths.get(yamlFilePath).toAbsolutePath();
            if (!Files.exists(path)) {
                System.err.println("YAML file not found: " + path);
                return null;
            }

            try (InputStream input = Files.newInputStream(path)) {
                Map<String, Object> result = yaml.load(input);
                if (result == null) {
                    System.err.println("Loaded YAML is null from: " + path);
                }
                return result;
            }
        } catch (Exception e) {
            System.err.println("Error loading YAML from " + yamlFilePath);
            e.printStackTrace();
            return null;
        }
    }
}