package application.system_under_test.tls_attacker;

import application.system_under_test.SystemUnderTest;
import application.system_under_test.tls_attacker.utils.TlsYamlParser;
import application.system_under_test.tls_attacker.utils.TlsMessageBuilder;
import application.system_under_test.tls_attacker.utils.TlsMessageParser;

import de.rub.nds.tlsattacker.core.config.Config;
import de.rub.nds.tlsattacker.core.connection.InboundConnection;
import de.rub.nds.tlsattacker.core.constants.RunningModeType;
import de.rub.nds.tlsattacker.core.protocol.message.ClientHelloMessage;
import de.rub.nds.tlsattacker.core.protocol.message.ServerHelloMessage;
import de.rub.nds.tlsattacker.core.state.State;
import de.rub.nds.tlsattacker.core.workflow.DefaultWorkflowExecutor;
import de.rub.nds.tlsattacker.core.workflow.WorkflowTrace;
import de.rub.nds.tlsattacker.core.workflow.action.ReceiveAction;
import de.rub.nds.tlsattacker.core.workflow.action.SendAction;

import java.util.Map;

/**
 * TLS-Attacker server implementation that extends SystemUnderTest.
 * This class handles TLS server operations including receiving ClientHello messages
 * and sending ServerHello responses.
 */
public class TLSAttackerServerRunner extends SystemUnderTest {

    /** The port number for the TLS server */
    private static final int PORT = 1234;

    /** Server configuration loaded from YAML */
    private Map<String, String> serverConfig;

    /** TLS-Attacker configuration */
    private Config config;

    /** Flag to control server running status */
    private boolean running = false;

    /**
     * Creates the System Under Test by initializing the TLS server configuration.
     */
    @Override
    public void createSUT() {
        // Load the abstract server configuration from YAML generated by the model
        this.serverConfig = TlsYamlParser.readYaml("src/main/resources/data/ModelServerHello.yaml");

        // Create TLS-Attacker configuration
        this.config = new Config();
        config.setDefaultRunningMode(RunningModeType.SERVER);
        config.setDefaultServerConnection(new InboundConnection(PORT));

        System.out.println("TLS Server initialized on port " + PORT);
    }

    /**
     * Starts the TLS server in a separate thread to listen for client connections.
     */
    @Override
    public void startSUT() {
        if (serverConfig == null || config == null) {
            System.err.println("Server not initialized. Call createSUT() first.");
            return;
        }

        running = true;

        new Thread(() -> {
            System.out.println("TLS Server starting on port " + PORT + "...");
            while (running) {
                try {
                    // New trace for each connection
                    WorkflowTrace trace = new WorkflowTrace();
                    trace.addTlsAction(new ReceiveAction(new ClientHelloMessage()));

                    // Build ServerHello dynamically
                    ServerHelloMessage serverHello = new ServerHelloMessage(config);
                    try {
                        TlsMessageBuilder.buildServerHello(serverConfig, serverHello, config);
                    } catch (UnsupportedOperationException e) {
                        System.err.println("Warning: " + e.getMessage());
                    }

                    trace.addTlsAction(new SendAction(serverHello));

                    // Execute session with fresh state
                    State state = new State(config, trace);
                    DefaultWorkflowExecutor executor = new DefaultWorkflowExecutor(state);
                    executor.executeWorkflow();

                    // Parse and store received ClientHello
                    ReceiveAction receiveAction = (ReceiveAction) state.getWorkflowTrace().getTlsActions().get(0);
                    if (!receiveAction.getReceivedMessages().isEmpty()) {
                        ClientHelloMessage clientHello = (ClientHelloMessage) receiveAction.getReceivedMessages().get(0);
                        Map<String, String> parsed = TlsMessageParser.parseClientHello(clientHello);
                        TlsYamlParser.writeYaml(parsed, "src/main/resources/data/SUTClientHello.yaml");
                        System.out.println("ClientHello received and saved.");
                    }

                } catch (Exception e) {
                    System.err.println("Error in server workflow: " + e.getMessage());
                    e.printStackTrace();
                }
            }
            System.out.println("TLS Server stopped.");
        }).start();
    }

    /**
     * Executes operations on the running server (not used in this setup).
     */
    @Override
    public void executeSUTOperation() {
        // No runtime operations for now
    }

    /**
     * Stops the TLS server.
     */
    public void stopServer() {
        running = false;
        System.out.println("Server stop requested.");
    }

    /**
     * Main method to run the server standalone.
     */
    public static void main(String[] args) {
        TLSAttackerServerRunner server = new TLSAttackerServerRunner();
        server.createSUT();
        server.startSUT();

        // Keep main thread alive
        try {
            Thread.sleep(Long.MAX_VALUE);
        } catch (InterruptedException e) {
            server.stopServer();
        }
    }
}
