package application.system_under_test.tls_attacker;

import application.system_under_test.SystemUnderTest;
import application.system_under_test.tls_attacker.utils.TlsYamlParser;
import application.system_under_test.tls_attacker.utils.TlsMessageBuilder;
import application.system_under_test.tls_attacker.utils.TlsMessageParser;

import de.rub.nds.tlsattacker.core.config.Config;
import de.rub.nds.tlsattacker.core.connection.OutboundConnection;
import de.rub.nds.tlsattacker.core.constants.CipherSuite;
import de.rub.nds.tlsattacker.core.constants.NamedGroup;
import de.rub.nds.tlsattacker.core.constants.RunningModeType;
import de.rub.nds.tlsattacker.core.protocol.message.ClientHelloMessage;
import de.rub.nds.tlsattacker.core.protocol.message.ServerHelloMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.KeyShareExtensionMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.SignatureAndHashAlgorithmsExtensionMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.SupportedVersionsExtensionMessage;
import de.rub.nds.tlsattacker.core.state.State;
import de.rub.nds.tlsattacker.core.workflow.DefaultWorkflowExecutor;
import de.rub.nds.tlsattacker.core.workflow.WorkflowTrace;
import de.rub.nds.tlsattacker.core.workflow.action.ReceiveAction;
import de.rub.nds.tlsattacker.core.workflow.action.SendAction;


import java.util.Arrays;
import java.util.List;
import java.util.Map;

/**
 * TLS-Attacker client implementation that extends SystemUnderTest.
 * This class handles TLS client operations including sending ClientHello messages
 * and processing ServerHello responses.
 */
public class TLSAttackerClientRunner extends SystemUnderTest {

    /** The hostname for the TLS connection */
    private static final String HOST = "localhost";
    
    /** The port number for the TLS connection */
    private static final int PORT = 1234;

    /**
     * Creates and executes the System Under Test.
     * Loads configuration from YAML, builds and sends a ClientHello message,
     * then processes the ServerHello response.
     */
    @Override
    public void createSUT() {
        // Load the abstract YAML generated by the model
        Map<String, String> clientHelloMap = TlsYamlParser.readYaml("src/main/resources/data/ModelClientHello.yaml");

        // Create TLS-Attacker configuration
        Config config = new Config();
        config.setDefaultRunningMode(RunningModeType.CLIENT);
        config.setDefaultClientConnection(new OutboundConnection(PORT, HOST));
        config.setWorkflowExecutorShouldClose(true);

        // Apply extensions from YAML
        ClientHelloMessage clientHello = new ClientHelloMessage(config);

        // Build clientHelloMessage
        TlsMessageBuilder.buildClientHello(clientHelloMap, clientHello, config);

        // Build workflow
        WorkflowTrace trace = new WorkflowTrace();
        trace.addTlsAction(new SendAction(clientHello));
        trace.addTlsAction(new ReceiveAction(new ServerHelloMessage()));

        // Execute workflow
        State state = new State(config, trace);
        DefaultWorkflowExecutor executor = new DefaultWorkflowExecutor(state);
        executor.executeWorkflow();

        // Extract and save received ServerHello
        ReceiveAction receiveAction = (ReceiveAction) state.getWorkflowTrace().getTlsActions().get(1);
        ServerHelloMessage response = (ServerHelloMessage) receiveAction.getReceivedMessages().get(0);

        Map<String, String> parsedResponse = TlsMessageParser.parseServerHello(response);
        TlsYamlParser.writeYaml(parsedResponse, "src/main/resources/data/SUTServerHello.yaml");

        System.out.println("ServerHello received and saved.");
    }

    /**
     * Starts the System Under Test.
     * Not required for this implementation.
     */
    @Override
    public void startSUT() {
        // Not needed for this implementation
    }

    /**
     * Executes operations on the System Under Test.
     * Not required for this implementation.
     */
    @Override
    public void executeSUTOperation() {
        // Not needed for this implementation
    }
}
