package application.system_under_test.tls_attacker;

import application.system_under_test.SystemUnderTest;
import application.system_under_test.tls_attacker.utils.ByteUtils;
import application.system_under_test.tls_attacker.utils.TlsMessageBuilder;
import application.system_under_test.tls_attacker.utils.TlsYamlParser;
// import application.information_handler.InformationConvertertoAbstract;

import java.util.LinkedHashMap;
import java.util.Map;

import de.rub.nds.tlsattacker.core.config.Config;
import de.rub.nds.tlsattacker.core.connection.OutboundConnection;
import de.rub.nds.tlsattacker.core.constants.CipherSuite;
// import de.rub.nds.tlsattacker.core.constants.NamedGroup;
// import de.rub.nds.tlsattacker.core.constants.ProtocolVersion;
import de.rub.nds.tlsattacker.core.constants.RunningModeType;
// import de.rub.nds.tlsattacker.core.protocol.handler.extension.PreSharedKeyExtensionHandler;
import de.rub.nds.tlsattacker.core.protocol.message.ClientHelloMessage;
import de.rub.nds.tlsattacker.core.protocol.message.ServerHelloMessage;
import de.rub.nds.tlsattacker.core.protocol.message.AlertMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.KeyShareExtensionMessage;
// import de.rub.nds.tlsattacker.core.protocol.message.extension.SignatureAndHashAlgorithmsExtensionMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.SupportedVersionsExtensionMessage;
import de.rub.nds.tlsattacker.core.state.State;
import de.rub.nds.tlsattacker.core.workflow.DefaultWorkflowExecutor;
import de.rub.nds.tlsattacker.core.workflow.WorkflowTrace;
import de.rub.nds.tlsattacker.core.workflow.action.ReceiveAction;
import de.rub.nds.tlsattacker.core.workflow.action.SendAction;

// import java.io.IOException;
// import java.nio.charset.StandardCharsets;
// import java.nio.file.Files;
// import java.nio.file.Path;
// import java.util.Arrays;
import java.util.LinkedHashMap;
// import java.util.List;
import java.util.Map;
// import java.util.LinkedHashMap;


/**
 * TLS-Attacker client implementation that extends SystemUnderTest.
 * This class handles TLS client operations including sending ClientHello messages
 * and processing ServerHello responses.
 */
public class TLSAttackerFakeClient extends SystemUnderTest {

    /** The hostname for the TLS connection */
    private static final String HOST = "localhost";

    /** The port number for the TLS connection */
    private static final int PORT = 8443;

    /** The path to the ClientHello YAML file to use (default: hardcoded model) */
    private String clientHelloYamlPath = "src/main/resources/data/ModelClientHello.yaml";

    /**
     * Sets the path to the ClientHello YAML file to use.
     * This allows using dynamically generated ClientHello instead of the hardcoded one.
     * 
     * @param yamlPath the path to the ClientHello YAML file
     */
    public void setClientHelloYamlPath(String yamlPath) {
        this.clientHelloYamlPath = yamlPath;
        System.out.println("ClientHello YAML path set to: " + yamlPath);
    }

    /**
     * Gets the current ClientHello YAML path.
     * 
     * @return the path to the ClientHello YAML file
     */
    public String getClientHelloYamlPath() {
        return this.clientHelloYamlPath;
    }

    /**
     * Creates and executes the System Under Test.
     * Loads configuration from YAML, builds and sends a ClientHello message,
     * then processes the ServerHello response.
     */
    @Override
    public void createSUT() {
        // Load the abstract YAML generated by the model
        Map<String, Object> yamlRoot = TlsYamlParser.readYamlAsObject(
            "src/main/resources/data/ModelClientHello.yaml"
        );

        // Extract clientHelloInformation section
        @SuppressWarnings("unchecked")
        Map<String, String> clientHelloMap = (Map<String, String>) yamlRoot.get("clientHelloInformation");
        
        if (clientHelloMap == null) {
            throw new RuntimeException("clientHelloInformation section not found in YAML");
        }

        // Debug: Print what was read from YAML
        System.out.println("DEBUG: YAML content read:");
        clientHelloMap.forEach((key, value) -> 
            System.out.println("  " + key + ": " + value)
        );

        // Create TLS-Attacker configuration
        Config config = new Config();
        config.setDefaultRunningMode(RunningModeType.CLIENT);
        config.setDefaultClientConnection(new OutboundConnection(PORT, HOST));
        config.setWorkflowExecutorShouldClose(true);

        // IMPORTANT: Configure cipher suites and other settings BEFORE creating ClientHello
        TlsMessageBuilder.configureFromYaml(clientHelloMap, config);

        // Create ClientHelloMessage with pre-configured settings
        ClientHelloMessage clientHello = new ClientHelloMessage(config);

        // Add extensions from YAML
        TlsMessageBuilder.addExtensionsToClientHello(clientHelloMap, clientHello);

        // Build workflow
        WorkflowTrace trace = new WorkflowTrace();
        trace.addTlsAction(new SendAction(clientHello));
        trace.addTlsAction(new ReceiveAction(new ServerHelloMessage()));

        // Execute workflow
        State state = new State(config, trace);
        DefaultWorkflowExecutor executor = new DefaultWorkflowExecutor(state);
        executor.executeWorkflow();

        // Extract and save received ServerHello
        ReceiveAction receiveAction = (ReceiveAction) state
            .getWorkflowTrace()
            .getTlsActions()
            .get(1);
            
        if (receiveAction.getReceivedMessages().isEmpty()) {
            System.err.println("ERROR: empty message received!");
            System.err.println("This usually indicates a connection failure or server rejection.");
            return;
        }
        
        Object receivedMessage = receiveAction.getReceivedMessages().get(0);
        System.out.println("Received message: " + receivedMessage.getClass().getSimpleName());
        
        // Check if we received an alert message instead of ServerHello
        if (receivedMessage instanceof AlertMessage) {
            AlertMessage alert = (AlertMessage) receivedMessage;
            // System.err.println("ERROR: Server sent alert message instead of ServerHello:");
            System.err.println("Alert Level: " + alert.getLevel().getValue());
            System.err.println("Alert Description: " + alert.getDescription().getValue());
            // System.err.println("\nThis indicates a problem with the ClientHello message:");
            // System.err.println("- Check TLS version compatibility");
            // System.err.println("- Verify cipher suite support");
            // System.err.println("- Ensure extensions are properly formatted");
            // System.err.println("- Consider using a simpler ClientHello configuration");
            return;
        }
        
        // Ensure we actually received a ServerHello
        if (!(receivedMessage instanceof ServerHelloMessage)) {
            System.err.println("ERROR: Expected ServerHello but received: " + receivedMessage.getClass().getSimpleName());
            return;
        }
        
        ServerHelloMessage response = (ServerHelloMessage) receivedMessage;

        System.out.println("ServerHello received successfully.");
        System.out.println(response.toString());
        // Map<String, String> parsedResponse = TlsMessageParser.parseServerHello(
        //     response
        // );
        // TlsYamlParser.writeYaml(
        //     parsedResponse,
        //     "src/main/resources/data/SUTServerHello.yaml"
        // );


        Map<String, String> parsed = new LinkedHashMap<>();
            parsed.put("random", ByteUtils.bytesToHex(response.getRandom().getValue()));
            
            // Pre-shared key should be '{}' for model compatibility
            parsed.put("pre_shared_key", "{}");
            
            // Session ID should be 'x' when empty for model compatibility
            if (response.getSessionId() != null && response.getSessionId().getValue() != null && response.getSessionId().getValue().length > 0) {
                parsed.put("legacy_session_id_echo", "x" + ByteUtils.bytesToHex(response.getSessionId().getValue()));
            } else {
                parsed.put("legacy_session_id_echo", "x");
            }
            
            parsed.put("legacy_version", "x" + ByteUtils.bytesToHex(response.getProtocolVersion().getValue()));
            
            // Supported versions should be '{TLS_1_3}' for model compatibility
            SupportedVersionsExtensionMessage supportedVersionsExt = response.getExtension(SupportedVersionsExtensionMessage.class);
            if (supportedVersionsExt != null && supportedVersionsExt.getSupportedVersions() != null) {
                parsed.put("supported_versions", "{TLS_1_3}");
            } else {
                parsed.put("supported_versions", "{TLS_1_3}");
            }
            
            // Compression methods should be '0' for model compatibility
            parsed.put("legacy_compression_methods", "0");
            
            // Key share should be '{}' for model compatibility
            parsed.put("key_share", "{}");
            
            // Cipher suite - ServerHello contains only ONE selected cipher suite (no braces)
            CipherSuite selectedCipherSuite = CipherSuite.getCipherSuite(response.getSelectedCipherSuite().getValue());
            if (selectedCipherSuite != null) {
                // For ServerHello: just the cipher suite name without braces
                parsed.put("cipher_suites", selectedCipherSuite.name());
            } else {
                parsed.put("cipher_suites", "UNKNOWN");
            }



        // Emballe dans la clé racine attendue par le modèle
        Map<String, Object> wrapped = Map.of("serverHelloInformation", parsed);

        // Écrit au format YAML
        TlsYamlParser.writeYaml(wrapped, "src/main/resources/data/SUTServerHello.yaml");

        // System.out.println(response.toString());
        System.out.println("ServerHello saved in YAML for ProB validation.");

        // ProtocolVersion version = ProtocolVersion.fromString("TLS13");
        // System.out.println("Protocol Version: " + version);
        
    }

    /**
     * Starts the System Under Test.
     * Not required for this implementation.
     */
    @Override
    public void startSUT() {
        // Not needed for this implementation
    }

    /**
     * Executes operations on the System Under Test.
     * Not required for this implementation.
     */
    @Override
    public void executeSUTOperation() {
        // Not needed for this implementation
    }
}
