package application.system_under_test.tls_attacker;

import application.system_under_test.SystemUnderTest;
import application.system_under_test.tls_attacker.utils.ByteUtils;
import application.system_under_test.tls_attacker.utils.TlsMessageBuilder;
import application.system_under_test.tls_attacker.utils.TlsMessageParser;
import application.system_under_test.tls_attacker.utils.TlsYamlParser;
import application.information_handler.InformationConvertertoAbstract;

import de.rub.nds.tlsattacker.core.config.Config;
import de.rub.nds.tlsattacker.core.connection.OutboundConnection;
import de.rub.nds.tlsattacker.core.constants.CipherSuite;
import de.rub.nds.tlsattacker.core.constants.NamedGroup;
import de.rub.nds.tlsattacker.core.constants.ProtocolVersion;
import de.rub.nds.tlsattacker.core.constants.RunningModeType;
import de.rub.nds.tlsattacker.core.protocol.handler.extension.PreSharedKeyExtensionHandler;
import de.rub.nds.tlsattacker.core.protocol.message.extension.PreSharedKeyExtensionMessage;
import de.rub.nds.tlsattacker.core.protocol.message.ClientHelloMessage;
import de.rub.nds.tlsattacker.core.protocol.message.ServerHelloMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.KeyShareExtensionMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.SignatureAndHashAlgorithmsExtensionMessage;
import de.rub.nds.tlsattacker.core.protocol.message.extension.SupportedVersionsExtensionMessage;
import de.rub.nds.tlsattacker.core.state.State;
import de.rub.nds.tlsattacker.core.workflow.DefaultWorkflowExecutor;
import de.rub.nds.tlsattacker.core.workflow.WorkflowTrace;
import de.rub.nds.tlsattacker.core.workflow.action.ReceiveAction;
import de.rub.nds.tlsattacker.core.workflow.action.SendAction;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.LinkedHashMap;


/**
 * TLS-Attacker client implementation that extends SystemUnderTest.
 * This class handles TLS client operations including sending ClientHello messages
 * and processing ServerHello responses.
 */
public class TLSAttackerFakeClient extends SystemUnderTest {

    /** The hostname for the TLS connection */
    private static final String HOST = "localhost";

    /** The port number for the TLS connection */
    private static final int PORT = 1234;

    /**
     * Creates and executes the System Under Test.
     * Loads configuration from YAML, builds and sends a ClientHello message,
     * then processes the ServerHello response.
     */
    @Override
    public void createSUT() {
        // Load the abstract YAML generated by the model
        Map<String, String> clientHelloMap = TlsYamlParser.readYaml(
            "src/main/resources/data/ModelClientHello.yaml"
        );

        // Create TLS-Attacker configuration
        Config config = new Config();
        config.setDefaultRunningMode(RunningModeType.CLIENT);
        config.setDefaultClientConnection(new OutboundConnection(PORT, HOST));
        config.setWorkflowExecutorShouldClose(true);

        // Apply extensions from YAML
        ClientHelloMessage clientHello = new ClientHelloMessage(config);

        // Build clientHelloMessage
        TlsMessageBuilder.buildClientHello(clientHelloMap, clientHello, config);

        // Build workflow
        WorkflowTrace trace = new WorkflowTrace();
        trace.addTlsAction(new SendAction(clientHello));
        trace.addTlsAction(new ReceiveAction(new ServerHelloMessage()));

        // Execute workflow
        State state = new State(config, trace);
        DefaultWorkflowExecutor executor = new DefaultWorkflowExecutor(state);
        executor.executeWorkflow();

        // Extract and save received ServerHello
        ReceiveAction receiveAction = (ReceiveAction) state
            .getWorkflowTrace()
            .getTlsActions()
            .get(1);
        ServerHelloMessage response = (ServerHelloMessage) receiveAction.getReceivedMessages().get(0);

        // Map<String, String> parsedResponse = TlsMessageParser.parseServerHello(
        //     response
        // );
        // TlsYamlParser.writeYaml(
        //     parsedResponse,
        //     "src/main/resources/data/SUTServerHello.yaml"
        // );


        Map<String, String> parsed = new LinkedHashMap<>();
            parsed.put("random", ByteUtils.bytesToHex(response.getRandom().getValue()));
            parsed.put("pre_shared_key", response.getExtension(PreSharedKeyExtensionMessage.class) != null ?
            response.getExtension(PreSharedKeyExtensionMessage.class).toString() : "{}");
            parsed.put("legacy_session_id_echo","x" + ByteUtils.bytesToHex(response.getSessionId().getValue()));
            parsed.put("legacy_version", "x"+ ByteUtils.bytesToHex(response.getProtocolVersion().getValue()));
            parsed.put("supported_versions", response.getExtension(SupportedVersionsExtensionMessage.class) != null ?
            response.getExtension(SupportedVersionsExtensionMessage.class).getSupportedVersions().toString() : "{TLS_1_3}");
            parsed.put("legacy_compression_methods", "0"); // constant for TLS 1.3
            parsed.put("key_share", response.getExtension(KeyShareExtensionMessage.class) != null ?
            response.getExtension(KeyShareExtensionMessage.class).getKeyShareList().toString() : "{}");
            // parsed.put("cipher_suites", ByteUtils.bytesToHex(response.getSelectedCipherSuite().getValue()));
            CipherSuite selectedCipherSuite = CipherSuite.getCipherSuite(response.getSelectedCipherSuite().getValue());
            parsed.put("cipher_suites", selectedCipherSuite != null ? selectedCipherSuite.name() : "UNKNOWN");



        // Emballe dans la clé racine attendue par le modèle
        Map<String, Object> wrapped = Map.of("serverHelloInformation", parsed);

        // Écrit au format YAML
        TlsYamlParser.writeYaml(wrapped, "src/main/resources/data/SUTServerHello.yaml");

        // System.out.println(response.toString());
        System.out.println("ServerHello saved in YAML for ProB validation.");

        ProtocolVersion version = ProtocolVersion.fromString("TLS13");
        System.out.println("Protocol Version: " + version);
        
    }

    /**
     * Starts the System Under Test.
     * Not required for this implementation.
     */
    @Override
    public void startSUT() {
        // Not needed for this implementation
    }

    /**
     * Executes operations on the System Under Test.
     * Not required for this implementation.
     */
    @Override
    public void executeSUTOperation() {
        // Not needed for this implementation
    }
}
